### PR TITLE
Fix compinit on zsh head

### PR DESCRIPTION
**Pull request by akatrevorjay**

### CODE REVIEW

**Comment by psprint** [comment]
Hello
Could you describe when -zplg-forget-completion() fails? I downloaded HEAD and ran zplg cominit with that version of Zsh, and it seems to work. Quite curious when "for i in.." can be run when $commands is empty. I did much conditions like your "[ -n "$k" ] || continue", but for (z) flag, which can return array or scalar, but regular "[@]" should always respect that $commands has zero elements and prevent any "for i in" from being run. This seems like Zsh bug for me. I now noticed that my $commands variable has the same name as zsh/parameter's "$commands" array, will change that, but first I will clarify your PR. Maybe the problem lies in the names being identical?

**Comment by akatrevorjay** [comment]
Actually that makes sense as to why it's happening.  It appeared as if
$_comps was not initialized as an array before compinit is ran, and this
worked around that edge case.

**Comment by psprint** [comment]
Could you provide more details about when the condition [ -n "$k" ] is needed? I'm trying to understand the patch before merging

**Comment by akatrevorjay** [comment]
Sure! ${commands[@]} expands to a single blank argument, ie set -- ""
I just added the quick check to make it portable since we're without nullglob.
There is most likely more story into why this is happening, but this works for the time being and I don't believe causes any side effects.

**Comment by akatrevorjay** [comment]
Does this repo have IRC or Gitter btw? I had something I wanted to run by you that's unrelated to an issue.

**Comment by psprint** [comment]
I confirm that following prints anything:

```
for i in "${(k@)_comps_notarr[(R)$f]}"; do echo "x $i x"; done
```

and $_comps can be not an array if compinit hasn't been ran before. Will merge

**Comment by psprint** [comment]
Yes there is IRC channel, #zplugin@freenode, but it's probably better to use emails, as I am lately rarely there

**Pull request merged**
